apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          # Ensure this is the tag containing the fixed services.py (v7 or latest)
          image: alexlee5541/sentiment-backend:v10
          env:
            - name: DATABASE_URL
              # FIX 1: The hostname MUST match the service name defined in database.yaml ('db-service')
              value: "postgresql://user:password@db-service:5432/sentiment_db" 
            - name: API_KEY
              # FIX 2: The environment variable name MUST be "API_KEY" to match os.getenv("API_KEY") in main.py
              # Since you are using hardcoded 'env', you must put your actual key here (NOT RECOMMENDED, but fixes the issue):
              value: "ofcsRnM0E5Y9IAtondELhM9xGxskcHTB" 
          # Resources are CORRECTLY placed here, under the container
          resources:
            requests:
              # Request enough memory to minimize startup swapping
              memory: "1024Mi" # Increased request to 1GB
              cpu: "500m"
            limits:
              # Set a high hard limit to allow the AI model to load
              memory: "2048Mi"